### PR TITLE
Use realistic file paths in file scopes

### LINKED ISSUE #462: url( ) local imports does not works with esbuild and esbuild-plugin plugin
### Describe the bug
Can not setup local url( ) import in css.ts files

### Link to reproduction
https://github.com/dmytro-shpak/esbuild-vanilla-extract-bug/
```
npm install
npm test
```

> Could not resolve "./x.svg" (the plugin "vanilla-extract" didn't set a resolve directory)`
### System Info

Output of `npx envinfo --system --npmPackages @vanilla-extract/css,@vanilla-extract/webpack-plugin,@vanilla-extract/esbuild-plugin,@vanilla-extract/vite-plugin,@vanilla-extract/sprinkles,webpack,esbuild,vite --binaries --browsers`:

```node
  System:
    OS: Linux 5.4 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
    Memory: 58.36 GB / 62.74 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  npmPackages:
    @vanilla-extract/css: ^1.6.3 => 1.6.3 
    @vanilla-extract/esbuild-plugin: ^2.0.0 => 2.0.0 
    esbuild: ^0.13.13 => 0.13.13 
```

### The workaround

Use babel for *.css.ts files
```
import babel from 'esbuild-plugin-babel';
```
```
        plugins: [
            babel({
                filter: /.*.css.ts/,
                config: {
                    presets: ['@babel/preset-typescript'],
                    plugins: ['@vanilla-extract/babel-plugin'],
                },
            }),
        ],
```

### LINKED ISSUE #631: Multiple CSS files have the same name when using the Vite plugin with a scoped package
### Describe the bug
If the package name includes a scope e.g `@vanilla-extract/example` the outputted CSS files will all have the names `example.vanilla.css`, `example.vanilla2.css`, `example.vanilla3.css` etc. This seems to be because the [sanitise file scope function](https://github.com/seek-oss/vanilla-extract/blob/4d45d8209bd26a9b2a8f9b5b8dfee9d420c3e45f/packages/integration/src/processVanillaFile.ts#L18) adds the package name and when a scope is used it includes a `/` so it considers the last part as the file name. I would expect the file name to be included in the asset name, which it is when not using a scope.

### Link to reproduction
https://stackblitz.com/edit/vitejs-vite-gfnuxw?file=vite.config.ts
- Run `npm run build` in the above and it outputs:
  ```
  vite v2.8.4 building for production...
  ✓ 9 modules transformed.
  dist/main.js                0.25 KiB / gzip: 0.20 KiB
  dist/main.css.js            0.18 KiB / gzip: 0.16 KiB
  dist/Button.js              0.13 KiB / gzip: 0.13 KiB
  dist/Heading.js             0.14 KiB / gzip: 0.14 KiB
  dist/Button.css.js          0.18 KiB / gzip: 0.16 KiB
  dist/Heading.css.js         0.18 KiB / gzip: 0.16 KiB
  dist/example.vanilla.css    0.23 KiB / gzip: 0.16 KiB
  dist/example.vanilla2.css   0.12 KiB / gzip: 0.13 KiB
  dist/example.vanilla3.css   0.04 KiB / gzip: 0.06 KiB
  ```
- However, if you remove the scope from `package.json->name`. It outputs the following:
  ```
  dist/main.js                                0.25 KiB / gzip: 0.20 KiB
  dist/main.css.js                            0.19 KiB / gzip: 0.15 KiB
  dist/Button.js                              0.13 KiB / gzip: 0.13 KiB
  dist/Heading.js                             0.14 KiB / gzip: 0.14 KiB
  dist/Button.css.js                          0.20 KiB / gzip: 0.16 KiB
  dist/Heading.css.js                         0.20 KiB / gzip: 0.16 KiB
  dist/Button.css.ts___example.vanilla.css    0.23 KiB / gzip: 0.17 KiB
  dist/main.css.ts___example.vanilla.css      0.12 KiB / gzip: 0.13 KiB
  dist/Heading.css.ts___example.vanilla.css   0.04 KiB / gzip: 0.06 KiB
  ```

### System Info

Output of `npx envinfo --system --npmPackages @vanilla-extract/css,@vanilla-extract/webpack-plugin,@vanilla-extract/esbuild-plugin,@vanilla-extract/vite-plugin,@vanilla-extract/sprinkles,webpack,esbuild,vite --binaries --browsers`:

```node
  System:
    OS: macOS 11.2.3
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 35.36 MB / 16.00 GB
    Shell: 5.8 - /usr/local/bin/zsh
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
  Browsers:
    Chrome: 99.0.4844.83
    Edge: 99.0.1150.46
    Firefox: 94.0.1
    Safari: 14.0.3
  npmPackages:
    @vanilla-extract/esbuild-plugin: ^2.0.3 => 2.0.3 
    @vanilla-extract/vite-plugin: ^3.1.2 => 3.1.2 
    esbuild: 0.14.22 => 0.14.22 
    vite: 2.8.4 => 2.8.4
```

### Related
- Some preliminary investigation was documented here:  https://github.com/seek-oss/vanilla-extract/discussions/620#discussioncomment-2409014

### PR DESCRIPTION
**Pull request by mattcompiles**
This PR is the start of getting rid of package names in file scopes, with the intention of using more realistic file paths for the app being compiled. This hopefully solves (or helps to solve) a bunch of issues with file resolution and file chunk naming.

Fixes #462
Fixes #631

### CODE REVIEW

**Comment by graup** [comment]
Looks good to me and does solve the file path problem. We should verify that this doesn't regress the fix for #427.

File: packages/esbuild-plugin/src/index.ts [hunk 1]
```diff
@@ -43,15 +45,20 @@ export function vanillaExtractPlugin({
...
-          let { source } = await getSourceFromVirtualCssFile(path);
+          let { source, fileName } = await getSourceFromVirtualCssFile(path);
 
           if (typeof processCss === 'function') {
             source = await processCss(source);
           }
 
+          const rootDir = build.initialOptions.absWorkingDir ?? process.cwd();
+
+          const resolveDir = dirname(join(rootDir, fileName));
```
Comment (dmytro-shpak) [inline packages/esbuild-plugin/src/index.ts:56]: may absWorkingDir end with '/'? probably
```
dirname(resolve(rootDir, fileName));
```
is the best option?

**Comment by mattcompiles** [comment]
@graup Thanks for reminding me about #427. I think it's possible this change could affect it. Thinking we should potentially make the filenames look absolute by prefixing with a `/`. That should hopefully stop any kind of automatic path processing from occurring as mentioned in the original issue. Will update this soon.

File: packages/esbuild-plugin/src/index.ts (hunk 1 above)
Comment (mattcompiles) [reply packages/esbuild-plugin/src/index.ts:56]: `path.join` handles the removal of duplicate slashes for you. I think `join` is better suited here.

File: packages/vite-plugin/src/index.ts [hunk 2]
```diff
@@ -60,50 +55,48 @@ export function vanillaExtractPlugin({ identifiers }: Options = {}): Plugin {
...
+      }
 
-        if (!server) {
-          return css;
-        }
+      const cssFileId = id.slice(config.root.length + 1);
+      const css = cssMap.get(cssFileId);
 
-        const fileScope = parseFileScope(fileScopeId);
+      if (!css) {
```
Comment (AndrewLeedham) [inline packages/vite-plugin/src/index.ts:78]: I was trying this code out locally and ran into a case where an empty CSS file would throw an error trying to load the `.css.ts.vanilla.css` file. This would allow an empty string to get through :)
```suggestion
      if (typeof css !== 'undefined') {
```

**Review by AndrewLeedham — CHANGES_REQUESTED** [review]

**Comment by mattcompiles** [comment]
@graup Looking to merge this soon. Happy with how it changes the rollup output? Seems cleaner to me but does make the custom asset file name test/docs a bit strange.

**Comment by graup** [comment]
> @graup Looking to merge this soon. Happy with how it changes the rollup output? Seems cleaner to me but does make the custom asset file name test/docs a bit strange.

It does but I'm fine with that. That's optional anyway, no big deal if users don't get that. It works fine with the default setting too.

**Review by michaeltaranto — APPROVED** [review]
LGTM
