### PR TITLE
Vite: Mark `.vanilla.js` and `.vanilla.css` modules as virtual.

### LINKED ISSUE #427: `@vanilla-extract/vite-plugin@^3` + `vite-tsconfig-paths` = Unable to locate /abc/def/vanillaStyles.css.ts$$$xxx in the CSS map.
### Describe the bug
`@vanilla-extract/vite-plugin` @ `v3.0.0` broke compatibility with `vite-tsconfig-paths`. After upgrading to `^3` the following is seen in the console when trying to combine with `vite-tsconfig-paths`

`[vite] Internal server error: Unable to locate /src/default/vanillaStyles.css.ts$$$xxx in the CSS map.`

Downgrading to ^2 fixes the problem.

### Link to reproduction

https://github.com/kompot/vite-vanilla-extract-tsconfig-paths-bug

### System Info

```node
  System:
    OS: macOS 11.5.2
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 135.09 MB / 16.00 GB
    Shell: 3.3.1 - /usr/local/bin/fish
  Binaries:
    Node: 16.10.0 - /usr/local/bin/node
    Yarn: 1.22.15 - /usr/local/bin/yarn
    npm: 7.24.0 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 89.1.21.77
    Chrome: 95.0.4638.54
    Edge: 94.0.992.47
    Firefox: 68.0.2
    Firefox Developer Edition: 94.0
    Safari: 14.1.2
    Safari Technology Preview: 15.0
  npmPackages:
    @vanilla-extract/css: ^1 => 1.6.2
    @vanilla-extract/vite-plugin: ^3 => 3.0.0
    @vanilla-extract/webpack-plugin: ^2 => 2.1.0
    vite: ^2.6 => 2.6.10
```

### PR DESCRIPTION
**Pull request by Katarina-UBCO**
Fixes #427 

Also see a different approach in this PR #457 

### The problem

When used with Vite, if `*.css.ts` module is imported from _outside_ of the root directory, the following error occurs:

```
Unable to locate /path-to.css.ts$$$@scope/package-name in the CSS map.
```

This happens, because the path `../path-to.css.ts` gets overridden to `/../path-to.css.ts` (by `vite:import-analysis`) and then consequently to `/path-to.css.ts` (by `vite.normalizePath`). As a result, `cssMap` stores the source under a different key as it is being retrieved.

This is where the source is stored under `../path-to.css.ts$$$@scope/package-name`:
https://github.com/seek-oss/vanilla-extract/blob/076b02d91f22d0b61df2dd9edd875f86ac4a55ea/packages/vite-plugin/src/index.ts#L152

This is where the we are trying to retrieve the source by wrong key (`/path-to.css.ts$$$@scope/package-name`):
https://github.com/seek-oss/vanilla-extract/blob/076b02d91f22d0b61df2dd9edd875f86ac4a55ea/packages/vite-plugin/src/index.ts#L69

### Solution

This PR should fix the problem, as it prefixes the relative paths with `vanilla-extract:` keyword which preserves the paths.

See [Vite Plugin Conventions](https://vitejs.dev/guide/api-plugin.html#conventions) for `virtual:` prefix.

### CODE REVIEW

File: packages/vite-plugin/src/index.ts [hunk 1]
```diff
@@ -16,6 +16,8 @@ import {
 const styleUpdateEvent = (fileId: string) =>
   `vanilla-extract-style-update:${fileId}`;
 
+const virtualPrefix = 'vanilla-extract:';
```
Comment (markdalgleish) [inline packages/vite-plugin/src/index.ts:19]: Based on the plugin conventions you linked to, should this prefix be `virtual:vanilla-extract/`?

Comment (Katarina-UBCO) [reply packages/vite-plugin/src/index.ts:19]: You're right, it looks like that it should be `virtual:vanilla-extract/` + path. (I first understood it as `virtual:` + path, and virtual could be replaced with the namespace, e.g. `vanilla-extract`). Anyway, it doesn't work with `virtual:vanilla-extract/` due to the `/` in the end. The relative path is being resolved incorrectly, e.g.

```
virtual:vanilla-extract/../design-system/src/theme.css.ts$$$@***/components.vanilla.js
```

is being resolved to 

```
/@id/design-system/src/theme.css.ts$$$@***/components.vanilla.js
```

which is resolved to

```
design-system/src/theme.css.ts$$$@***/components.vanilla.js
```

Which doesn't exist.

Removing `/` from `virtual:vanilla-extract/` (or replacing it with `:` or `-`) solves the problem. Maybe we should stick to something like `/@ve-css` (as described in https://github.com/seek-oss/vanilla-extract/pull/457) or use something like `/@vanilla-extract` ?

Thanks heaps for your help and love your work 🥇

File: packages/vite-plugin/src/index.ts [hunk 2]
```diff
@@ -56,15 +58,17 @@ export function vanillaExtractPlugin({ identifiers }: Options = {}): Plugin {
       packageInfo = getPackageInfo(config.root);
     },
     resolveId(id) {
-      if (id.indexOf(virtualExt) > 0) {
+      if (id.startsWith(virtualPrefix) && id.indexOf(virtualExt) > 0) {
```
Comment (mattcompiles) [inline packages/vite-plugin/src/index.ts:61]: Think we can drop the virtualExt check now as it's basically redundant. Also we prefer to use `indexOf` instead of `startsWith` as it seems to be quite a lot more performant.

File: packages/vite-plugin/src/index.ts [hunk 3]
```diff
@@ -56,15 +58,17 @@ export function vanillaExtractPlugin({ identifiers }: Options = {}): Plugin {
...
         return id;
       }
     },
     load(id) {
       const extensionIndex = id.indexOf(virtualExt);
 
-      if (extensionIndex > 0) {
-        const fileScopeId = id.substring(0, extensionIndex);
+      if (id.startsWith(virtualPrefix) && extensionIndex > 0) {
```
Comment (mattcompiles) [inline packages/vite-plugin/src/index.ts:68]: Think we can drop the `extensionIndex` check here as well as it's now redundant. This means we can pull the `extensionIndex` variable into the if block scope as well.

File: packages/vite-plugin/src/index.ts [hunk 4]
```diff
@@ -56,15 +58,17 @@ export function vanillaExtractPlugin({ identifiers }: Options = {}): Plugin {
...
+        const fileScopeId = id
+          .substring(0, extensionIndex)
+          .slice(virtualPrefix.length);
```
Comment (mattcompiles) [inline packages/vite-plugin/src/index.ts:71]: This can be done through one call to `slice`. e.g. `slice(virtualPrefix.length, extensionIndex)`

**Review by mattcompiles — COMMENTED** [review]
This approach is seeming much cleaner. 👍  Just a couple of small implementation comments.

File: packages/vite-plugin/src/index.ts (hunk 1 above)
Comment (mattcompiles) [reply packages/vite-plugin/src/index.ts:19]: Could we make the prefix `virtual:vanilla-extract:` then?

Comment (Katarina-UBCO) [reply packages/vite-plugin/src/index.ts]: @mattcompiles set to `virtual:vanilla-extract:` thank you

File: packages/vite-plugin/src/index.ts (hunk 4 above)
Comment (Katarina-UBCO) [reply packages/vite-plugin/src/index.ts]: Very good point. Done. Thank you

File: packages/vite-plugin/src/index.ts (hunk 3 above)
Comment (Katarina-UBCO) [reply packages/vite-plugin/src/index.ts]: Done these, too.

File: packages/vite-plugin/src/index.ts (hunk 2 above)
Comment (Katarina-UBCO) [reply packages/vite-plugin/src/index.ts]: Done these, too.

File: .changeset/calm-ravens-sit.md [hunk 5]
```diff
@@ -0,0 +1,5 @@
+---
+'@vanilla-extract/vite-plugin': patch
+---
+
+Prefix `.vanilla.js` and `.vanilla.css` virtual modules with `vanilla-extract:`.
```
Comment (mattcompiles) [inline .changeset/calm-ravens-sit.md:5]:
```suggestion
Prefix `.vanilla.js` and `.vanilla.css` virtual modules with `virtual:vanilla-extract:`.
```

**Review by mattcompiles — APPROVED** [review]
Awesome work. 👏  Thanks for all the effort.

**Comment by Katarina-UBCO** [comment]
Thanks heaps @mattcompiles 🎉 Team work!
