### PR TITLE
vite/rollup: Return empty sourcemaps

### LINKED ISSUE #699: Vite: Sourcemap warning suppression
### Describe the bug
When building an app using vite and vanilla extract, and when the [build.sourcemap](https://vitejs.dev/config/#build-sourcemap) vite config option is set to true, I receive a bunch of sourcemap warnings. 
i.e.
```
vite v2.9.9 building for production...
✓ 15216 modules transformed.
rendering chunks (2)...Sourcemap is likely to be incorrect: a plugin (vanilla-extract) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help
Sourcemap is likely to be incorrect: a plugin (vanilla-extract) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help
Sourcemap is likely to be incorrect: a plugin (vanilla-extract) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help
Sourcemap is likely to be incorrect: a plugin (vanilla-extract) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help
Sourcemap is likely to be incorrect: a plugin (vanilla-extract) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help
Sourcemap is likely to be incorrect: a plugin (vanilla-extract) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help
Sourcemap is likely to be incorrect: a plugin (vanilla-extract) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help
Sourcemap is likely to be incorrect: a plugin (vanilla-extract) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help
Sourcemap is likely to be incorrect: a plugin (vanilla-extract) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help
Sourcemap is likely to be incorrect: a plugin (vanilla-extract) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help
...
```
The vanilla extract docs list a way to supress this warning for esbuild:
https://github.com/seek-oss/vanilla-extract#esbuild

but I haven't found a way to suppress them for Vite. Would love to be able to suppress these if possible.

### System Info

Output of `npx envinfo --system --npmPackages @vanilla-extract/css,@vanilla-extract/webpack-plugin,@vanilla-extract/esbuild-plugin,@vanilla-extract/vite-plugin,@vanilla-extract/sprinkles,webpack,esbuild,vite --binaries --browsers`:

```node
  System:
    OS: macOS 12.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 3.75 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.1 - ~/.asdf/installs/nodejs/16.13.1/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.3.0 - ~/.asdf/plugins/nodejs/shims/npm
  Browsers:
    Chrome: 101.0.4951.64
    Firefox: 100.0.2
    Safari: 15.3
  npmPackages:
    @vanilla-extract/css: ^1.6.8 => 1.6.8
    @vanilla-extract/vite-plugin: ^3.1.6 => 3.1.6
    @vanilla-extract/webpack-plugin: ^2.1.5 => 2.1.10
    vite: ^2.9.9 => 2.9.9
```

### PR DESCRIPTION
**Pull request by graup**
Fixes #699 

This suppresses the warnings in vite and rollup.

I'm not sure this is really what we want though. Logically this is wrong and the warning actually is correct.

### CODE REVIEW

File: packages/rollup-plugin/src/index.ts [hunk 1]
```diff
@@ -81,14 +85,18 @@ export function vanillaExtractPlugin({
...
         const assetId = emittedFiles.get(importPath)!;
         const assetName = this.getFileName(assetId);
         const fixedImportPath = `./${normalize(
           relative(chunkPath, assetName),
         )}`;
         return codeResult.replace(importPath, fixedImportPath);
       }, code);
+      return {
+        code: output,
+        map: chunkInfo.map ?? null,
```
Comment (mattcompiles) [inline packages/rollup-plugin/src/index.ts:98]: Is `null` handled differently than `undefined`?

Comment (graup) [reply packages/rollup-plugin/src/index.ts:98]: Yes it seems so. When I tested it `chunkInfo.map` actually was undefined and still resulted in the same warning. But with `null` it is suppressed.

**Review by mattcompiles — APPROVED** [review]
