### PR TITLE
Fix createThemeVars when using null values

### LINKED ISSUE #44: Issues with themeContracts handling null values
Hello 👋 

Very excited about vanilla-extract and wanted to give it a try in Framer with esbuild.

Unfortunately, I'm having some difficulties with the output. I wonder if this could be a bug with the esbuild plugin, or perhaps a mistake on my end!!

Here are my files:
```typescript
// definitions.ts
import { createThemeVars } from "@vanilla-extract/css"

export const theme = createThemeVars({
    color: {
        tint: null,
        tintDark: null,
    },
})
```

```typescript
// dark.css.ts
import { createTheme } from "@vanilla-extract/css"
import { theme } from "./definitions"

export const dark = createTheme(
    theme,
    {
        color: {
            tint: "#0099ff",
            tintDark: "#0088ff",
        },
    },
    "dark-theme"
)
```

Elsewhere, I import `dark` and consume it in react:
```typescript
import { dark } from "./dark.css"
// ...

<div className={dark}>
```

My output from esbuild is then: 
```css
/* vanilla-extract-css-ns:vekter/../fresco/src/tokens/colors/theme/dark.css.ts.vanilla.css?source=LmRhcmtfZGFyay10aGVtZV9fMWt1cWlxMTAgewogIG51bGw6ICMwMDg4ZmY7Cn0= */
.dark_dark-theme__1kuqiq10 {
  null: #0088ff;
}
```

Dependencies:
```json
"@vanilla-extract/css": "^0.3.0",
"@vanilla-extract/esbuild-plugin": "^0.1.2",
```

### PR DESCRIPTION
**Pull request by mattcompiles**
Resolves #44

### CODE REVIEW

**Review by michaeltaranto — APPROVED** [review]

File: packages/private/src/walkObject.ts [hunk 1]
```diff
@@ -1,26 +1,37 @@
...
+    ) {
+      clone[key] = fn(value as Primitive, currentPath);
+    } else if (typeof value === 'object' && !Array.isArray(value)) {
+      clone[key] = walkObject(value as Walkable, fn, currentPath);
     } else {
       console.warn(
         `Skipping invalid key "${currentPath.join(
           '.',
-        )}". Should be a string, number or object. Received: "${typeof value}"`,
+        )}". Should be a string, number or object. Received: "${
```
Comment (markdalgleish) [inline packages/private/src/walkObject.ts:32]: Should this mention `null`?

**Review by markdalgleish — APPROVED** [review]
Just a question about the error message, but otherwise looks good 👍

**Review by jahredhope — APPROVED** [review]
