### PR TITLE
Handle pre-compiled `createTheme` destructuring in Babel plugin

### LINKED ISSUE #369: Next.js: Warning `prop` className did not match. Server: "generated_server_className" Client: "generated_client_className"
### Describe the bug

After next.js compiles it throws a runtime error with something along the lines of:
```javascript
Warning: Prop `className` did not match. Server: "pages_themeClass__sryalf0" Client: "pages__createTheme__sryalf0"
```

### Link to reproduction

I have a fork of next.js that has an example of vanilla-extract with [typescript](https://github.com/jaycedotbin/next.js/tree/canary/examples/with-vanilla-extract-typescript) and [javascript](https://github.com/jaycedotbin/next.js/tree/canary/examples/with-vanilla-extract-javascript)

### System Info

Output of `npx envinfo --system --npmPackages @vanilla-extract/css,@vanilla-extract/webpack-plugin,@vanilla-extract/esbuild-plugin,@vanilla-extract/vite-plugin,@vanilla-extract/sprinkles,webpack,esbuild,vite --binaries --browsers`:

```node
  System:
    OS: Linux 5.14 Arch Linux
    CPU: (4) x64 AMD A8-7600 Radeon R7, 10 Compute Cores 4C+6G
    Memory: 341.82 MB / 6.74 GB
    Container: Yes
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.6 - ~/.local/share/volta/tools/image/node/14.17.6/bin/node
    npm: 6.14.15 - ~/.local/share/volta/tools/image/node/14.17.6/bin/npm
  Browsers:
    Brave Browser: 93.1.29.81
  npmPackages:
    @vanilla-extract/css: ^1.6.0 => 1.6.0
```

### PR DESCRIPTION
**Pull request by markdalgleish**
Fixes #369

### CODE REVIEW

File: packages/babel-plugin/src/index.ts [hunk 1]
```diff
@@ -87,6 +87,31 @@ const getDebugId = (path: NodePath<t.CallExpression>) => {
...
+    t.isVariableDeclaration(firstRelevantParentPath.parent) &&
+    firstRelevantParentPath.parent.declarations.length === 4
+  ) {
+    const [themeDeclarator, , classNameDeclarator] =
+      firstRelevantParentPath.parent.declarations;
+
+    if (
+      t.isCallExpression(themeDeclarator.init) &&
+      t.isIdentifier(themeDeclarator.init.callee) &&
+      themeDeclarator.init.callee.name === 'createTheme' &&
```
Comment (mattcompiles) [inline packages/babel-plugin/src/index.ts:107]: This can be shortened to:
```js
t.isIdentifier(themeDeclarator.init.callee, { name: 'createTheme' })
```

File: packages/babel-plugin/src/index.ts [hunk 2]
```diff
@@ -87,6 +87,31 @@ const getDebugId = (path: NodePath<t.CallExpression>) => {
     return;
   }
 
+  // Special case: Handle `export const [themeClass, vars] = createTheme({});`
+  // when it's already been compiled into this:
+  //
+  // var _createTheme = createTheme({}),
+  //   _createTheme2 = _slicedToArray(_createTheme, 2),
```
Comment (mattcompiles) [inline packages/babel-plugin/src/index.ts:94]: Should we add any checking to see if this line is related to the `createTheme` call? Just want to be sure we don't get any false positives?

Comment (markdalgleish) [reply packages/babel-plugin/src/index.ts:94]: Considered this but thought it's probably overkill given it's already constrained to variable declarations defining 4 variables where the first one calls `createTheme` — something that effectively never happens naturally. How strongly do you feel on this one?

Comment (mattcompiles) [reply packages/babel-plugin/src/index.ts:94]: Not strongly 👍

**Review by mattcompiles — APPROVED** [review]
Nice one 👍

File: packages/babel-plugin/src/index.ts (hunk 1 above)
Comment (markdalgleish) [reply packages/babel-plugin/src/index.ts]: Cool, didn't know you could do that. Pushed a refactor.
